import { Baloo_2 } from 'next/font/google'
import Header from './components/Header'
import Footer from './components/Footer'
import styles from './page.module.css'
import './globals.css'

const baloo = Baloo_2({
  weight: ['400', '500', '600'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={baloo.className}>
        <Header />
        <main className={styles.main}>
          <section className={styles.mainSection}>
            <div className={styles.wrapper}>
              <div className={styles.content}>{children}</div>
            </div>
          </section>
        </main>
        <Footer />
      </body>
    </html>
  )
}
